apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    pv.beta.kubernetes.io/gid: "8983"
  generation: 1
  labels:
    app: testbed-solr
    release: testbed-solr
  name: testbed-solr
  namespace: testbed
  selfLink: /apis/apps/v1/namespaces/testbed/statefulsets/testbed-solr
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: solr
      release: testbed-solr
  serviceName: testbed-solr
  template:
    metadata:
      labels:
        app: solr
        app.kubernetes.io/instance: testbed-solr
        app.kubernetes.io/name: solr
        chart: solr-0.1.0
        heritage: Helm
        release: testbed-solr
    spec:
      containers:
      - env:
        - name: SOLR_DATA_HOME
          value: /solrdata
        image: dtobtn/testbed-solr:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /solr/admin/info/system
            port: 8983
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: testbed-solr
        ports:
        - containerPort: 8983
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /solr/admin/info/system
            port: 8983
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 3000Mi
          requests:
            cpu: ".5"
            memory: 512Mi
        securityContext:
          runAsUser: 8983
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /solrdata
          name: data
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 8983
      serviceAccount: testbed-solr
      serviceAccountName: testbed-solr
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: testbed-solr
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      annotations:
        pv.beta.kubernetes.io/gid: "8983"
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 75Gi
      volumeMode: Filesystem
