apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: testbed-solr
    app.kubernetes.io/name: solr
    app.kubernetes.io/version: "1"
  name: testbed-solr
  namespace: testbed
  selfLink: /api/v1/namespaces/testbed/services/testbed-solr
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30983
    port: 8983
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: testbed-solr
    app.kubernetes.io/name: solr
  sessionAffinity: None
  type: NodePort
